/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.EstudianteControlador;
import Modelo.Pregunta;
import Modelo.PreguntaCerrada;
import Modelo.Prueba;
import java.awt.CardLayout;
import java.util.List;

/**
 *
 * @author Daniela Chaux
 */
public class PnlPrueba extends javax.swing.JPanel implements FormularioVisitador {

    /**
     * Creates new form Prueba
     */
    public PnlPrueba() {
        initComponents();
        numeroPregunta = 0;
        pnlPruebaPrincipal.ponerTexto(EstudianteControlador.getInstance().getPrueba().getDescripcion());
        iniciarFormulario();
    }
    private FormularioVisitador formulario;
    private Prueba prueba;
    private int numeroPregunta;
    public FormularioVisitador getFormulario() {
        return formulario;
    }

    public void setFormulario(FormularioVisitador formulario) {
        this.formulario = formulario;
    }
    

    public void cambiarTarjeta(String tarjeta) {
        System.out.println("Numero Pregunta:" + numeroPregunta);
        System.out.println("Tamaño:"+ prueba.getPreguntas().size());
        ((CardLayout) PnlPreguntas.getLayout()).show(PnlPreguntas, tarjeta);
        if(tarjeta.equals("Atras")){
            if(numeroPregunta > 0){
                numeroPregunta--;
                mostrarPregunta();
            }
            else{
                pnlPreguntaAbierta.desactivarBotones();
                pnlPreguntaCerrada.desactivarBotones();
            }
        }    
        else if(tarjeta.equals("Siguiente")){
            if(numeroPregunta + 1< prueba.getPreguntas().size()){
                numeroPregunta++;
                mostrarPregunta();
            }
            else{
                pnlPreguntaAbierta.desactivarBotones();
                pnlPreguntaCerrada.desactivarBotones();
            }
        }
        else if(tarjeta.equals("")){
            mostrarPregunta();
        }
        else if(tarjeta.equals("PreguntaAbierta")){
            pnlPreguntaAbierta.limpiarTexto();
        }
        else if(tarjeta.equals("PreguntaCerrada")){
            pnlPreguntaCerrada.limpiarTexto();
        }
        
    }
    public void cambiarTarjetaAbuelo(String tarjeta){
        formulario.cambiarTarjeta(tarjeta);
        EstudianteControlador.getInstance().guardarPruebaArchivo();
        
    }

    public void iniciarFormulario(){
        pnlPruebaPrincipal.setFormulario(this);
        pnlPreguntaAbierta.setFormulario(this);
        pnlPreguntaCerrada.setFormulario(this);
        prueba = EstudianteControlador.getInstance().getPrueba();
    }
    public void mostrarPregunta(){
        String enunciado = prueba.getPreguntas().get(numeroPregunta).getEnunciado();
        int numero = prueba.getPreguntas().get(numeroPregunta).getNumero();
        if(prueba.getPreguntas().get(numeroPregunta) instanceof PreguntaCerrada){
            cambiarTarjeta("PreguntaCerrada");
            List <String> respuestas = ((PreguntaCerrada) prueba.getPreguntas().get(numeroPregunta)).getRespuesta();
            pnlPreguntaCerrada.ponerTextos(enunciado,respuestas, numero) ;

        }
        else if(prueba.getPreguntas().get(numeroPregunta) instanceof Pregunta){
            cambiarTarjeta("PreguntaAbierta");
            pnlPreguntaAbierta.ponerTextos(enunciado, numero);
        }
        else{
            System.out.println("NO ENTRO");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlPreguntas = new javax.swing.JPanel();
        pnlPruebaPrincipal = new Vista.PnlPruebaPrincipal();
        pnlPreguntaAbierta = new Vista.PnlPreguntaAbierta();
        pnlPreguntaCerrada = new Vista.PnlPreguntaCerrada();

        PnlPreguntas.setLayout(new java.awt.CardLayout());
        PnlPreguntas.add(pnlPruebaPrincipal, "card4");
        PnlPreguntas.add(pnlPreguntaAbierta, "PreguntaAbierta");
        PnlPreguntas.add(pnlPreguntaCerrada, "PreguntaCerrada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PnlPreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PnlPreguntas, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlPreguntas;
    private Vista.PnlPreguntaAbierta pnlPreguntaAbierta;
    private Vista.PnlPreguntaCerrada pnlPreguntaCerrada;
    private Vista.PnlPruebaPrincipal pnlPruebaPrincipal;
    // End of variables declaration//GEN-END:variables
}
